language: python

python:
  - 3.6

matrix:
  include:
    - name: "Tests + Coverage: Python 3.6"
      python: "3.6"
      install:
        - pip install cython numpy
        - pip install git+https://github.com/cornellius-gp/gpytorch.git
        - pip install git+https://github.com/pytorch/botorch.git
        - pip install -q -e .[dev,mysql,notebook]
      script:
        - pytest -ra --cov=ax
    - name: "Tests: Python 3.7"
      # Enable Python 3.7 w/o without globally enabling sudo and xenial dist
      # See https://github.com/travis-ci/travis-ci/issues/9815
      python: "3.7"
      dist: xenial
      install:
        - pip install cython numpy
        - pip install git+https://github.com/cornellius-gp/gpytorch.git
        - pip install git+https://github.com/pytorch/botorch.git
        - pip install -q -e .[dev,mysql,notebook]
      script:
        - pytest -ra
    - name: "Lint: black (Python 3.6)"
      python: "3.6"
      install:
        - pip install black
      script:
        - black --check --diff .
    - name: "Lint: flake8 (Python 3.6)"
      python: "3.6"
      install:
        - pip install flake8
      script:
        # don't use .flake8 config for now, since don't need custom plugin
        - flake8 --isolated --ignore=T484,T499,W503,E704,E231,E203 --max-line-length=88
    - name: "Docs: Sphinx (Python 3.6)"
      python: "3.6"
      install:
        - pip install cython numpy
        - pip install git+https://github.com/cornellius-gp/gpytorch.git
        - pip install git+https://github.com/pytorch/botorch.git
        - pip install -q -e .[dev,mysql,notebook,gpy]
      script:
        # warnings treated as errors
        - sphinx-build -WT sphinx/source sphinx/build
        # since -W flag breaks on first error, re-run without it to print all
        - sphinx-build sphinx/source sphinx/build

deploy:
  provider: script
  script: bash scripts/publish_site.sh
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
